[build]
  publish = "public"
  command = "echo 'Deploying...'"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[dev]
  command = "yarn start"
  targetPort = 3000

[identity]
  enabled = true  # Active Netlify Identity

[backend]
  name = "git-gateway"